import type { Metadata } from "next";

import { Inter_Tight } from "next/font/google";

import "./globals.css";
import { Header } from "@/components/Header";
import { LenisProvider } from "@/components/LenisProvider";

const inter = Inter_Tight({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${inter.variable} h-full antialiased`} lang="en">
      <body className="min-h-full flex flex-col">
        <LenisProvider>
          <main className="max-w-7xl m-auto">
            <Header />
            {children}
          </main>
        </LenisProvider>
      </body>
    </html>
  );
}
